import { Product } from '@/types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'opc',
    name: 'Ordinary Portland Cement (OPC)',
    name_en: 'Ordinary Portland Cement (OPC)',
    name_zh: '普通硅酸盐水泥',
    tagline: 'Semen Tipe 1 untuk Konstruksi Umum',
    tagline_en: 'Type 1 Cement for General Construction',
    tagline_zh: '通用建筑用1型水泥',
    description: 'Semen Portland Tipe 1 berkualitas tinggi yang dirancang untuk berbagai aplikasi konstruksi umum, memberikan kekuatan awal yang tinggi dan daya tahan jangka panjang.',
    description_en: 'High-quality Type 1 Portland Cement designed for various general construction applications, providing high early strength and long-term durability.',
    description_zh: '高质量的1型硅酸盐水泥，专为各种通用建筑应用设计，提供早期高强度和长期耐久性。',
    features: ['Kuat tekan tinggi', 'Setting time optimal', 'Warna konsisten'],
    features_en: ['High compressive strength', 'Optimal setting time', 'Consistent color'],
    features_zh: ['抗压强度高', '凝结时间最佳', '颜色一致'],
    applications: ['Gedung bertingkat', 'Jembatan', 'Jalan raya', 'Perumahan'],
    applications_en: ['High-rise buildings', 'Bridges', 'Highways', 'Housing'],
    applications_zh: ['高层建筑', '桥梁', '高速公路', '住宅'],
    specs: { 'Kuat Tekan 28 Hari': '45 MPa', 'Setting Time Awal': '120 menit' },
    specs_en: { '28-Day Compressive Strength': '45 MPa', 'Initial Setting Time': '120 mins' },
    specs_zh: { '28天抗压强度': '45 MPa', '初凝时间': '120分钟' },
    color: 'Abu-abu',
    status: 'active',
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '2',
    slug: 'pcc',
    name: 'Portland Composite Cement (PCC)',
    name_en: 'Portland Composite Cement (PCC)',
    name_zh: '复合硅酸盐水泥',
    tagline: 'Semen Serbaguna Ramah Lingkungan',
    tagline_en: 'Eco-friendly Multipurpose Cement',
    tagline_zh: '环保多用途水泥',
    description: 'Semen komposit yang diformulasikan khusus untuk menghasilkan permukaan yang lebih halus dan kedap air, serta lebih ramah lingkungan.',
    description_en: 'Specially formulated composite cement to produce smoother and watertight surfaces, while being more environmentally friendly.',
    description_zh: '特制复合水泥，可产生更光滑和防水的表面，同时更加环保。',
    features: ['Permukaan halus', 'Kedap air', 'Panas hidrasi rendah'],
    features_en: ['Smooth surface', 'Watertight', 'Low heat of hydration'],
    features_zh: ['表面光滑', '防水', '水化热低'],
    applications: ['Plesteran', 'Acian', 'Pasangan bata', 'Beton pracetak'],
    applications_en: ['Plastering', 'Skimming', 'Bricklaying', 'Precast concrete'],
    applications_zh: ['抹灰', '面层', '砌砖', '预制混凝土'],
    specs: { 'Kuat Tekan 28 Hari': '40 MPa', 'Kehalusan': '380 m²/kg' },
    specs_en: { '28-Day Compressive Strength': '40 MPa', 'Fineness': '380 m²/kg' },
    specs_zh: { '28天抗压强度': '40 MPa', '细度': '380 m²/kg' },
    color: 'Abu-abu Terang',
    status: 'active',
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '3',
    slug: 'white-cement',
    name: 'White Portland Cement',
    name_en: 'White Portland Cement',
    name_zh: '白色硅酸盐水泥',
    tagline: 'Semen Putih untuk Estetika',
    tagline_en: 'White Cement for Aesthetics',
    tagline_zh: '美学用白水泥',
    description: 'Semen putih premium dengan tingkat keputihan tinggi, ideal untuk aplikasi arsitektural dan dekoratif.',
    description_en: 'Premium white cement with high whiteness, ideal for architectural and decorative applications.',
    description_zh: '高白度优质白水泥，非常适合建筑和装饰应用。',
    features: ['Putih cemerlang', 'Daya rekat kuat', 'Tahan cuaca'],
    features_en: ['Brilliant white', 'Strong adhesion', 'Weather resistant'],
    features_zh: ['洁白亮丽', '附着力强', '耐候'],
    applications: ['Dekorasi interior', 'Terrazzo', 'Nat keramik', 'Patung'],
    applications_en: ['Interior decoration', 'Terrazzo', 'Grout', 'Sculptures'],
    applications_zh: ['室内装饰', '水磨石', '灌浆', '雕塑'],
    specs: { 'Derajat Keputihan': '> 85%', 'Kuat Tekan 28 Hari': '35 MPa' },
    specs_en: { 'Whiteness Degree': '> 85%', '28-Day Compressive Strength': '35 MPa' },
    specs_zh: { '白度': '> 85%', '28天抗压强度': '35 MPa' },
    color: 'Putih',
    status: 'active',
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '4',
    slug: 'oil-well',
    name: 'Oil Well Cement',
    name_en: 'Oil Well Cement',
    name_zh: '油井水泥',
    tagline: 'Semen Khusus Industri Migas',
    tagline_en: 'Special Cement for Oil & Gas Industry',
    tagline_zh: '石油和天然气工业专用水泥',
    description: 'Semen khusus yang dirancang untuk tahan terhadap tekanan dan suhu tinggi serta serangan sulfat, cocok untuk pengeboran sumur minyak dan gas.',
    description_en: 'Special cement designed to withstand high pressure, temperature, and sulfate attack, suitable for oil and gas well drilling.',
    description_zh: '专为承受高压、高温和硫酸盐侵蚀而设计的水泥，适用于油气井钻探。',
    features: ['Tahan sulfat tinggi', 'Tahan suhu tinggi', 'Setting time terkontrol'],
    features_en: ['High sulfate resistance', 'High temperature resistance', 'Controlled setting time'],
    features_zh: ['高抗硫酸盐', '耐高温', '凝结时间可控'],
    applications: ['Sumur minyak', 'Sumur gas', 'Geothermal'],
    applications_en: ['Oil wells', 'Gas wells', 'Geothermal'],
    applications_zh: ['油井', '气井', '地热'],
    specs: { 'Kelas': 'G (HSR)', 'Thickening Time': '100 menit' },
    specs_en: { 'Class': 'G (HSR)', 'Thickening Time': '100 mins' },
    specs_zh: { '等级': 'G (HSR)', '稠化时间': '100分钟' },
    color: 'Abu-abu Gelap',
    status: 'active',
    sort_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];
